import string, random, multiprocessing
from PIL import Image
import numpy as np
from pathlib import Path
from functools import partial

def generate_amino_acid_color_map()->dict:
  """Function to map every amino acid in a RGB color

  Returns:
      dict: amino_acid:color map
  """
  amino_acid_color_map = {}
  possible_colors = ((255,204,153),
                    (255,180,102),
                    (255, 204,204),
                    (153,255,51),
                    (0,255,0) ,
                    (0,204,102) ,
                    (0,153,153),
                    (0,51,102),
                    (0,0,51 ),
                    (51,0,51) ,
                    (102,0,102),
                    (176,0,153) ,
                    (0,0,204),
                    (0,128,255),
                    (51,255,255),
                    (102,255,178),
                    (153,255, 153),
                    (229,255,204),
                    (102,0,0),
                    (102,90,0), 
                    (0,102,102),
                    (25,0,51) ,
                    (204,0,102) ,
                    (96,96,96) ,
                    (255,51,255),
                    (120,120,120))
  for index, amino_acid in enumerate(string.ascii_uppercase):
      amino_acid_color_map[amino_acid] = possible_colors[index]
  return amino_acid_color_map


def sequence2Image(Sequence:str, height:int=800, width:int=1333, amino_acid_color_map:dict={})->Image:
  """
    Function to convert sequence to Image

  Args:
      Sequence (str): [description]
      height (int, optional): [description]. Defaults to 800.
      width (int, optional): [description]. Defaults to 1333.
      amino_acid_color_map (dict, optional): [description]. Defaults to {}.

  Returns:
      Image: [description]
  """
  # create a blank image
  img_arr = np.zeros((height,width,3)) # numpy takes images in H, W, D order, PIL in (W, H)

  # fill RGB colors to each pixel
  num_rows = img_arr.shape[0]
  num_cols = img_arr.shape[1]
  for row_indx in range(num_rows):
    for column_indx in range(num_cols):
      if column_indx < len(Sequence):
        img_arr[row_indx, column_indx, :] = amino_acid_color_map[Sequence[column_indx]]
      else:
        img_arr[row_indx, column_indx, :] = [255, 255, 255]
  return Image.fromarray(img_arr.astype(np.uint8))

def save_sequence2Image(item)->None:
  """Function to save image generated by sequence2Image

  Args:
      item ([type]): [description]
  """
  sequence, seq_id, class_name, super_class_name, save_dir, par_sequence2Image = item
  img = par_sequence2Image(sequence)
  if not (save_dir/f'{class_name}').exists():
    (save_dir/f'{class_name}').mkdir(parents=True, exist_ok=True)
  img.save(save_dir/f"{class_name}/{super_class_name}_{class_name}_{seq_id}.png")

def create_image_dataset(sequences:list, sequence_ids:list, class_name:str, super_class_name:str, save_dir:Path)->None:
  """
  Function to create images for list of sequences of a given class in save_dir
  with img names as superClassName_className_sequenceID.png

  Args:
      sequences (list): [description]
      sequences (list): [description]
      class_name (str): [description]
      super_class_name (str): [description]
      save_dir (Path): [description]
  """
  amino_acid_color_map = generate_amino_acid_color_map()
  par_sequence2Image = partial(sequence2Image, height=800, width=1333, amino_acid_color_map=amino_acid_color_map)
  items = [(sequence, seq_id, class_name, super_class_name, save_dir, par_sequence2Image) for sequence, seq_id in zip(sequences, sequence_ids)]
  # for item in items:
  #   save_sequence2Image(item)
  with multiprocessing.Pool(processes=multiprocessing.cpu_count()) as p:
    p.map(save_sequence2Image, items)

if __name__ == "__main__":
  # amino_acid_color_map = generate_amino_acid_color_map()
  # sequence2Image("".join([random.choice(string.ascii_uppercase) for i in range(650)]), amino_acid_color_map=amino_acid_color_map).save('img.png')
  from Bio import SeqIO
  records = []
  ids = []
  for record in SeqIO.parse('/Volumes/SatishJ/ML/Orbuculum/ProteinDomainDetection/PF05257_seed.txt','fasta'):
    records.append(record.seq._data)
    ids.append(record.id.split('/')[0])
  create_image_dataset(records[:4],ids[:4],'PF05257', 'CHAP',Path('/Volumes/SatishJ/ML/Orbuculum/ProteinDomainDetection/data/imgs/'))
 